# id|folder|binary|description
Desktop.Export|Desktop.Export|Desktop.Export|Servico dedicado a exportacao de dados do Desktop
Desktop.Import|Desktop.Import|Desktop.Import|Servico dedicado a importacao de dados do Desktop
Desktop.Instance|Desktop.Instance|Desktop.Instance|Servico dedicado a gerenciamento de instancias do Desktop
Desktop.Integration|Desktop.Integration|Desktop.Integration|Servico dedicado a integracao de dados do Desktop
Desktop.InterfaceAPI|Desktop.InterfaceAPI|Desktop.InterfaceAPI|Servico dedicado a API de interface do Desktop
